import {
  ArgumentsHost,
  BadRequestException,
  Catch,
  ExceptionFilter,
  HttpException,
  InternalServerErrorException,
} from '@nestjs/common';
import { FastifyReply } from 'fastify';

@Catch()
export class ErrorResponseNormalizerFilter implements ExceptionFilter {
  async catch(rawException: Error, host: ArgumentsHost) {
  
    
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<FastifyReply>();

    // Verificar si la excepciÃ³n es de tipo HttpException
    const exception =
    rawException instanceof HttpException
    ? rawException
    : new InternalServerErrorException();
    
    console.log("ðŸš€ ~ file: error-response-normalizer.filter.ts:22 ~ ErrorResponseNormalizerFilter ~ exception:", exception)
    const status = exception.getStatus();
    const generalMessage = this.getGeneralMessage(exception);

    // Enviar la respuesta de error personalizada
    await response.status(status).send({
      status: status,
      message: generalMessage,
      errors: this.mapToErrors(exception),
    });
  }

  private mapToErrors(error: HttpException) {
    console.log("ðŸš€ ~ file: error-response-normalizer.filter.ts:35 ~ ErrorResponseNormalizerFilter ~ mapToErrors ~ error:", error)
    const response = error.getResponse();

    
    // Si tiene un array de errores, devolvemos los errores tal como estÃ¡n
    if (typeof response === 'object' && Array.isArray(response['errors'])) {
      return response['errors'];
    }

    // Si tiene un campo especÃ­fico y un mensaje Ãºnico
    if (typeof response === 'object' && response['field']) {
      return [{ field: response['field'], reason: response['message'] }];
    }

    // Si no se encuentra ninguna estructura especÃ­fica, devolver un mensaje genÃ©rico
    return [{ field: null, reason: error.message }];
  }

  private getGeneralMessage(error: HttpException): string {
    const response = error.getResponse();
    return typeof response === 'object' && response['message'] ? response['message'] : error.message;
  }
}
